article/api/urls.py
from django.urls import path, include 
from . import views
from rest_framework import routers 

router = routers.DefaultRouter()
router.register(r'article', views.ArticleViewSet)

app_name = 'blog_project'

urlpatterns = [
     path('',include(router.urls)),
]


'''
     path('article/',
         views.ArticleListView.as_view(),
         name='article_list'),

     path('article/<pk>/',
         views.ArticleDetailView.as_view(),
         name='article_detail'),

     path('article/create',
         views.ArticleCreateView.as_view(),
         name='article_create'),
         '''

article/urls.py
from django.urls import path

from .views import (
    ArticleListView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleCreateView,
    #post
)
urlpatterns = [
    path('new/', ArticleCreateView.as_view(), name = 'article_new'),
    path('', ArticleListView.as_view(), name ='article_list'),
    path('<slug>/edit/', ArticleUpdateView.as_view(), name = 'article_edit'),
    path('<slug>/delete/', ArticleDeleteView.as_view(), name = 'article_delete'),
    path('<slug>/', ArticleDetailView.as_view(), name = 'article_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', TemplateView.as_view(template_name="about.html"), name="about"),
    path('admin/', admin.site.urls),
    path('',include('article.urls')),
    path('api/', include('article.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
import os
from django.template.defaultfilters import slugify
from django.shortcuts import get_object_or_404
  
class ArticleManager(models.Manager):
    use_for_related_fields = True

    def active(self, *args, **kwargs):
        return super(ArticleManager, self).filter(draft=False).filter(pub_date__lte=timezone.now())
'''
    def images(self, slug):
        article = None
        article= get_object_or_404(Article,slug=slug)
        images = Images.objects.filter(article__in=[article])
        return images
'''
def upload_location(instance, filename):
    PostModel = instance.__class__
    title = instance.article.title
    slug = slugify(title)
    return os.path.join( "article_images/%s-%s" % (slug, filename))


class Article(models.Model):
    title = models.CharField(max_length = 255, verbose_name= "Title")
    slug= models.SlugField(unique=True)
    body = models.TextField( verbose_name= "body")
    modified = models.DateTimeField(auto_now = True)
    draft = models.BooleanField(default=False)
    pub_date = models.DateField(auto_now=False, auto_now_add=False, blank=True,null=True)
    objects = ArticleManager()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article,self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-pub_date", "-modified"]

class Images(models.Model):
    article = models.ForeignKey(Article, default=None, on_delete = models.CASCADE)
    image = models.ImageField(upload_to=upload_location,
            null=True,
            blank=True)

article/forms.py
from django import forms
from .models import Article, Images
from django.forms.models import modelformset_factory

class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='title')
        
    class Meta:
        model = Article
        fields = ('title', 'body', )
        

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Images
        fields = ('image', )


ImageFormSet = modelformset_factory(Images,form=ImageForm, extra=3)

article/api/views.py
from rest_framework import generics, viewsets
from ..models import Article
from .serializers import ArticleSerializer
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated

class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

article/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy,reverse
from .models import Article, Images
from django.shortcuts import get_object_or_404, render
from django.forms import modelformset_factory
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import ImageForm, ArticleForm, ImageFormSet
from django.db import transaction


class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'

    def get_queryset(self):
        return Article.objects.active

class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = kwargs["object"]
        context['images'] = Images.objects.filter(article__title = article)
        return context

class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article_list')
    login_url = 'login'

class ArticleUpdateView(LoginRequiredMixin,UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article_edit.html'
    login_url = 'login'


class ArticleCreateView(LoginRequiredMixin,CreateView):
    model = Article
    fields = ['title','body']

    template_name = 'article_new.html'
    login_url = 'login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['article_form'] = ArticleForm(self.request.POST)
            context['formset'] = ImageFormSet(self.request.POST,
                                              self.request.FILES,
                                              queryset=Images.objects.none())
        else:
            context['article_form'] = ArticleForm()
            context['formset'] = ImageFormSet(queryset=Images.objects.none())
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        article_form = context['article_form']
        formset = context['formset']
        if article_form.is_valid() and formset.is_valid():
            article_form = article_form.save(commit=False)
            article_form.save()
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    photo = Images(article=article_form, image=image)
                    photo.save()
            return redirect(article_form.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
'''

def post(request):
    if request.method == 'POST':

        articleForm = ArticleForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if articleForm.is_valid() and formset.is_valid():
            article_form = articleForm.save(commit=False)
            article_form.save()

            for form in formset.cleaned_data:
                #this helps to not crash if the user
                #do not upload all the photos
                if form:
                    image = form['image']
                    photo = Images(article=article_form, image=image)
                    photo.save()
            return HttpResponseRedirect("/")
        else:
            print(articleForm.errors, formset.errors)
    else:
        articleForm = ArticleForm()
        formset = ImageFormSet(queryset=Images.objects.none())
    return render(request, 'article_new.html',
                  {'articleForm': articleForm, 'formset': formset})
                  '''

templates/about.html
{% extends 'base.html' %}


{% block content%}






<h1 id="about-me">About me</h1>

<p>I’m a full stack developer and educator based in Boston. I’ve written <a href="https://wsvincent.com/books">two (soon to be three)</a> books on Django and co-host the <a href="https://djangochat.com">Django Chat Podcast</a>.</p>

<p>Previously I worked at numerous early-stage startups, most notably <a href="http://quizlet.com/">Quizlet</a>, and taught computer science at <a href="http://williams.edu/">Williams College</a>. Outside of programming I’m an <a href="https://wsvincent.com/reading">avid reader</a>.</p>

<p>To stay up-to-date on new tutorials please sign up for <a href="/newsletter">my monthly newsletter</a>!</p>


<h2 id="selected-projects">Selected Projects</h2>

<ul>
  <li><a href="https://github.com/wsvincent/djangox">DjangoX</a> - starter framework for new Django projects</li>
  <li><a href="https://github.com/wsvincent/drfx">DRFX</a> - starter framework for new Django REST Framework projects</li>
  <li><a href="https://github.com/wsvincent/awesome-django">Awesome Django</a> - curated list of awesome Django resources</li>
  <li><a href="https://sqljs.org/">SQLjs</a> - online SQL interpreter</li>
  <li><a href="/htmlescapetool/">HTML Escape Tool</a> - automatically escape/unescape HTML code</li>
</ul>


{% endblock %}

templates/article_comment.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

templates/article_delete.html
{% extends 'base.html' %}

{% block content%}
	<h1> Delete </h1>
	<form action="" method="post">{% csrf_token %}
		<p>Are you sure you want to delete "{{article.title }}"? </p>
		<button class = "btn btn-danger ml-2" type = "submit" >Confirm</button>
	</form>
{% endblock content%}

templates/article_detail.html
{% extends 'base.html' %}


{% block content%}
<div class="article-entry" >
	<h2 class="content-markdown"> {{ object.title }}</h2>
		<p> {{ object.pub_date|date:"N d Y"  }} </p>
		<div class="thumbnail">
					 {% if images %}
						 {% for image in images%}
								<img src='{{ image.image.url }}' class='img-responsive' />
							{% endfor %}
					 {% endif %}
		</div>
		<div >
		<p class="content-markdown">{{ object.body }}</p>
	</div>
</div>

	<div id="disqus_thread"></div>

<script>
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://paigel.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>

{% endblock content%}

templates/article_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
	<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

		<div id="container">
            <h3>Title:</h3>
        	<input class="editable medium-editor-textarea" 
				name="title" 
				type="text"
				id="id_title"
				value = "{{ object.title }}"
			{{ object.title }}>
		</div>

		<div id="container">
	        <h3>Body:</h3>
        	<textarea class="editable medium-editor-textarea " name="body" >
				{{object.body}}
			</textarea>
    	</div>
		
		<button class = "btn btn-info ml-2" type = "submit" >Update</button>
	</form>

{% endblock content%}

{% block js %}
	<script src="{% static 'js/medium-editor.js' %}"></script>
{% endblock js %}

templates/article_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content%}
	{% for article in object_list %}
		<div class = "card" >
			<div class="card-header">
				<a href="{% url 'article_detail' article.slug %}">
				<span class = "font-weight-bold">{{ article.title }}</span>
			</a>
			</div>
			<div class="card-body">
				<h6 class = " text -muted"> {{article.pub_date|date:"d N Y" }}</h6>
		<br />
	{% endfor %}
{% endblock content%}

templates/article_new.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

	<h2> New Article </h2>
	<form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in article_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

						<div id="container">
              {{ article_form.title.label_tag }}
              <input
                type="text"
                class="form-control"
                id="id_title"
                name="title"
                placeholder="Your name"
                value="{{ article_form.title.value|default:'' }}" >
              {% if form.title.errors %}
                <div class="invalid-feedback">
                  {{ form.title.errors }}
                </div>
              {% endif %}
            </div>
    <div id="container">
        <textarea class="editable medium-editor-textarea " name="body" >{{article_form.body.value|default:""}}</textarea>
    </div>


    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}
			<button class = "btn btn-success ml-2" type = "submit" >Save</button>
	</form>
{% endblock content%}

     {% block js %}
<script src="{% static 'js/medium-editor.js' %}"></script>
      {% endblock js %}

templates/base.html
{% load static %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>Peizhi Zheng</title>
  <meta name="description" content="Peizhi Zheng is a python/Django software engineer">
  <link  rel="stylesheet" href="{% static 'css/medium-editor.css' %}">
  <link  rel="stylesheet" href="{% static 'css/medium-editor.min.css' %}">
  <link  rel="stylesheet" href="{% static 'css/demo.css' %}">
  <link rel='stylesheet' href='https://d33wubrfki0l68.cloudfront.net/css/0c4f68edea9a98fbd953bec63439515e9492c58f/assets/main.css'/>
  <link rel="canonical" href="https://paigel.com/">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.23.3/css/medium-editor.min.css'/>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.23.3/css/themes/beagle.css'/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.23.3/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css">


</head>
<body class="site">

  <header>
  <div class="container-flex">
    <div class="nav-wrapper">
      <div class="nav-left">
        <a href="/">Peizhi Zheng</a></li>
      </div>
      <div class="nav-right">
        <a class="about-link" href="/about">About</a>
        <a class="about-link" href="/newsletter">Newsletter</a>
      </div>
    </div>
  </div>
</header>
<main class="site-content">
   <div class="container-flex">


      {% block content %}
      {% endblock content %}
      {% block js %}
      {% endblock js %}
    </div>
  </main>
  <footer>
<div class="container-flex">
  <div class="nav-wrapper">
    <div class="nav-left">
      © Peizhi Zheng
      <!-- <a href="/">Home</a>
      <a href="/projects">Projects</a>
      <a href="/about">About</a>
      <a href="https://github.com/wsvincent">Github</a> -->
    </div>
    <div class="nav-right">
      <a href="mailto:parisa1206@gmail.com">Parisa1206@gmail.com</a>
    </div>
  </div>
</div>
</footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4\
    YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/\
    JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"> </script>
    <script type="text/javascript">
    
    $(document).ready(function(){
      $(".content-markdown").each(function(){
        var content = $(this).text()
        console.log(content)
        var markedContent = marked(content)
        console.log(markedContent)
        $(this).html(markedContent)
    })
    $(".content-markdown img").each(function(){
           $(this).addClass("img-responsive");
   })
  })
    </script>
    <script id="dsq-count-scr" src="//paigel.disqus.com/count.js" async></script>
  </body>
</html>

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
	<form method = "post">
		{% csrf_token %}
		{{ form|crispy }}
		<button class = 'btn btn-success'type="submit"> Sign Up </button>
	</form>
{% endblock content %}